<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <Authors>shadesofdeath</Authors>
    <Product>ShadeUI</Product>
    <Copyright>Copyright © 2026 shadesofdeath</Copyright>
  </PropertyGroup>
</Project>
